### ISSUE TITLE
GUID conflict when importing as package

### ISSUE THREAD

**Issue by krisrok** [TRS6123/AginerianInput#1]
`GUID [b1015158cf6c7df4c8d77d9320ce2e7c] for asset 'Packages/com.aginerian.input/Runtime/ClosestFloatToZeroComparer.cs.meta' conflicts with:
  'Packages/com.aginerian.input/Runtime/LowestMagnitudeFloatComparer.cs.meta'
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.`

**Comment by TRS6123** [comment]
For some reason the repo kept both ClosestFloatToZeroComparer and LowestMagnitudeFloatComparer after renaming the former to the latter. I deleted the former file as it is not needed.
